[2015-07-19T22:16:19.724600] [dn52es6g.sunet] [24136_1] [StackDump] Initiating stack dump for all threads
ActiveThreadCount: 8
KnownActiveThreadNames:
  MainThread
  StatusUpdate-Thread
  TaskManager-Thread
  TaskRunner-Thread-copy_SHIP2046638_tar
  TaskRunner-Thread-copy_SHIP2022990_tar
  TaskRunner-Thread-copy_SHIP2028102_tar
  TaskRunner-Thread-masterWorkflow
  TaskRunner-Thread-copy_SHIP2036847_tar

Thread: 4337590272 TaskRunner-Thread-copy_SHIP2046638_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4337315840 TaskRunner-Thread-copy_SHIP2022990_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4335177728 TaskManager-Thread
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1556, in run
  self.tdag.isFinishedEvent.wait(5)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 620, in wait
  self.__cond.wait(timeout)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 358, in wait
  _sleep(delay)

Thread: 4334628864 StatusUpdate-Thread
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3775, in _runUpdate
  stackDump(stackDumpFp)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 512, in stackDump
  for filename, lineno, name, line in traceback.extract_stack(stack):

Thread: 4335452160 TaskRunner-Thread-copy_SHIP2028102_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4334903296 TaskRunner-Thread-masterWorkflow
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1049, in _run
  retval = self.workflow._waitForTasksCore(namespace, isVerbose=False)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3663, in _waitForTasksCore
  ewaiter.wait()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 442, in wait
  time.sleep(self.sec)

Thread: 140735295836928 MainThread
File: "transfer_from_drive.py", line 118, in <module>
File: "transfer_from_drive.py", line 46, in transfer_data
  print "Transfer failed!  See logs for details. %s" % LOG_DIR
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3081, in run
  retval = self._runWorkflow(param)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3812, in _runWorkflow
  ewaiter.wait()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 444, in wait
  self.event.wait(self.sec)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 620, in wait
  self.__cond.wait(timeout)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 358, in wait
  _sleep(delay)

Thread: 4337041408 TaskRunner-Thread-copy_SHIP2036847_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)


[2015-07-19T23:16:19.835327] [dn52es6g.sunet] [24136_1] [StackDump] Initiating stack dump for all threads
ActiveThreadCount: 8
KnownActiveThreadNames:
  MainThread
  StatusUpdate-Thread
  TaskManager-Thread
  TaskRunner-Thread-copy_SHIP2046638_tar
  TaskRunner-Thread-copy_SHIP2022990_tar
  TaskRunner-Thread-copy_SHIP2028102_tar
  TaskRunner-Thread-masterWorkflow
  TaskRunner-Thread-copy_SHIP2036847_tar

Thread: 4337590272 TaskRunner-Thread-copy_SHIP2046638_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4337315840 TaskRunner-Thread-copy_SHIP2022990_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4335177728 TaskManager-Thread
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1556, in run
  self.tdag.isFinishedEvent.wait(5)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 620, in wait
  self.__cond.wait(timeout)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 358, in wait
  _sleep(delay)

Thread: 4334628864 StatusUpdate-Thread
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3775, in _runUpdate
  stackDump(stackDumpFp)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 512, in stackDump
  for filename, lineno, name, line in traceback.extract_stack(stack):

Thread: 4335452160 TaskRunner-Thread-copy_SHIP2028102_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)

Thread: 4334903296 TaskRunner-Thread-masterWorkflow
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1049, in _run
  retval = self.workflow._waitForTasksCore(namespace, isVerbose=False)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3663, in _waitForTasksCore
  ewaiter.wait()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 442, in wait
  time.sleep(self.sec)

Thread: 140735295836928 MainThread
File: "transfer_from_drive.py", line 118, in <module>
File: "transfer_from_drive.py", line 46, in transfer_data
  if not return_value == 0:
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3081, in run
  retval = self._runWorkflow(param)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 3812, in _runWorkflow
  ewaiter.wait()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 444, in wait
  self.event.wait(self.sec)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 620, in wait
  self.__cond.wait(timeout)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 358, in wait
  _sleep(delay)

Thread: 4337041408 TaskRunner-Thread-copy_SHIP2036847_tar
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 995, in run
  (retval, retmsg) = self._run()
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1118, in _run
  self.runOnce(retInfo)
File: "/Library/Python/2.7/site-packages/pyflow/pyflow.py", line 1174, in runOnce
  retInfo.retval = proc.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
  pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  return func(*args)


